name: 'kafka'
version: 0.1.0
description: Kafka Client library for Dartlang

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  quiver: ^3.1.0
  logging: ^1.0.2

dev_dependencies:
  test:
  mockito: ^5.3.0